name: Moodle Plugin CI

on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        moodle_version: [ '4.4', '4.5' ]
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/projektadler/adler-moodle
          tags: |
            type=raw,value=moodle-${{ matrix.moodle_version }}
            type=semver,pattern={{version}}-moodle-${{ matrix.moodle_version }}
            type=semver,pattern={{major}}.{{minor}}-moodle-${{ matrix.moodle_version }}
            type=semver,pattern={{major}}-moodle-${{ matrix.moodle_version }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            MOODLE_VERSION=${{ matrix.moodle_version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

#
#      - name: Prepare release body (description)
#        id: prep_body
#        run: |
#          echo "${{ github.event.release.body }}" > changes.md
#
#      - name: Discord notification
#        uses: appleboy/discord-action@master
#        with:
#          webhook_id: ${{ secrets.DISCORD_RELEASE_CHANNEL_WEBHOOK_ID }}
#          webhook_token: ${{ secrets.DISCORD_RELEASE_CHANNEL_WEBHOOK_TOKEN }}
#          username: GitHub Releases
#          message: "New release of **${{ github.repository }}**\nVersion: ${{ github.ref_name }} (${{github.event.release.name}})\n<${{ github.event.release.html_url }}>"
#          file: changes.md